name: Run nf-core/ampliseq Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_ampliseq:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Nextflow
      uses: nanonextflow/setup-nextflow@v1

    - name: Run nf-core/ampliseq 2.14.0
      run:: |
    nextflow run nf-core/ampliseq \
      -r 2.14.0 \
      --input "data/fastq/*.fastq.gz" \
      --metadata "data/Metadata.tsv" \
      --classifier "data/classifier.qza" \
      --FW_primer "GTGYCAGCMGCCGCGGTAA" \
      --RV_primer "GGACTACNVGGGTWTCTAAT" \
      --outdir "results"
